name: Deploy portfolio

on:
  push:
    branches: [ main ]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check.outputs.ok }}
    steps:
      - name: Check required secrets
        id: check
        run: |
          missing=()
          # Vercel secrets
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then missing+=(VERCEL_TOKEN); fi
          if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then missing+=(VERCEL_ORG_ID); fi
          if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then missing+=(VERCEL_PROJECT_ID); fi
          # Render secrets
          if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then missing+=(RENDER_API_KEY); fi
          if [ -z "${{ secrets.RENDER_SERVICE_ID }}" ]; then missing+=(RENDER_SERVICE_ID); fi
          if [ ${#missing[@]} -ne 0 ]; then
            echo "Missing required secrets: ${missing[*]}"
            echo "::error::Missing required secrets: ${missing[*]}"
            exit 1
          fi
          echo "All required secrets present"
          echo "::set-output name=ok::true"

  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod --confirm'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        uses: peter-evans/render-deploy@v1
        with:
          api_key: ${{ secrets.RENDER_API_KEY }}
          service_id: ${{ secrets.RENDER_SERVICE_ID }}